package com.example.alothmanysender;

import android.app.*;import android.content.*;import android.content.pm.*;import android.graphics.*;import android.os.*;import android.provider.Settings;import android.text.InputType;import android.view.*;import android.widget.*;import java.util.*;

public final class MainActivity extends Activity {
    AppState state; LinkEngine engine; UI ui;
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(0,28,34));getWindow().setNavigationBarColor(Color.rgb(0,18,22));state=new AppState(this);engine=new LinkEngine(state);ui=new UI(this);engine.setListener(s->{ui.status=s;ui.refresh();});setContentView(ui);}
    void chooseWhatsapp(){
        PackageManager pm=getPackageManager();ArrayList<String> pkgs=new ArrayList<>();ArrayList<String> names=new ArrayList<>();
        String[] candidates={"com.whatsapp","com.whatsapp.w4b","com.obwhatsapp","com.gbwhatsapp","com.yowhatsapp"};
        for(String p:candidates)try{ApplicationInfo a=pm.getApplicationInfo(p,0);pkgs.add(p);names.add(pm.getApplicationLabel(a)+"\n"+p);}catch(Exception ignored){}
        if(pkgs.isEmpty()){Toast.makeText(this,"لم يتم العثور على واتساب في ملف المستخدم الحالي",Toast.LENGTH_LONG).show();return;}
        new AlertDialog.Builder(this).setTitle("اختر تطبيق واتساب").setItems(names.toArray(new String[0]),(d,w)->{state.selectedPackage(pkgs.get(w));ui.refresh();}).setNegativeButton("إلغاء",null).show();
    }
    void chooseLinks(){EditText e=new EditText(this);e.setHint("chat.whatsapp.com/... كل رابط في سطر");e.setGravity(Gravity.TOP|Gravity.RIGHT);e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE|InputType.TYPE_TEXT_VARIATION_URI);e.setMinLines(8);new AlertDialog.Builder(this).setTitle("إضافة روابط").setView(e).setNegativeButton("إلغاء",null).setPositiveButton("حفظ",(d,w)->{ArrayList<String>l=new ArrayList<>();LinkedHashSet<String>seen=new LinkedHashSet<>();for(String s:e.getText().toString().split("\\R")){s=s.trim();if(s.startsWith("https://chat.whatsapp.com/")&&seen.add(s))l.add(s);}state.links(l);state.index(0);state.clearFailed();ui.refresh();Toast.makeText(this,"تم حفظ "+l.size()+" رابط بدون تكرار",Toast.LENGTH_SHORT).show();}).show();}
    void editMessage(){EditText e=new EditText(this);e.setText(state.message());e.setHint("اكتب الرسالة التي تريد نشرها");e.setGravity(Gravity.TOP|Gravity.RIGHT);e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);e.setMinLines(5);new AlertDialog.Builder(this).setTitle("رسالة النشر").setView(e).setNegativeButton("إلغاء",null).setPositiveButton("حفظ",(d,w)->{state.message(e.getText().toString());ui.refresh();}).show();}
    void start(){if(state.selectedPackage().isEmpty()){chooseWhatsapp();return;}if(state.links().isEmpty()){chooseLinks();return;}if(state.publishEnabled()&&state.message().trim().isEmpty()){editMessage();return;}engine.start(state.links());}
    void pause(){if(state.paused())engine.resume();else engine.pause();}
    void stop(){engine.stop();}
    void accessibility(){try{startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS));}catch(Exception e){Toast.makeText(this,"تعذر فتح إعدادات الوصول",Toast.LENGTH_LONG).show();}}
    void openWhatsapp(){String p=state.selectedPackage();if(p.isEmpty()){chooseWhatsapp();return;}try{Intent i=getPackageManager().getLaunchIntentForPackage(p);if(i!=null)startActivity(i);else Toast.makeText(this,"تعذر فتح واتساب",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"تعذر فتح واتساب",Toast.LENGTH_LONG).show();}}

    final class UI extends View {
        Paint p=new Paint(3);LinkEngine.Status status;float den;RectF r=new RectF();int bg=Color.rgb(2,29,34),card=Color.rgb(4,39,45),line=Color.rgb(0,120,128),cyan=Color.rgb(0,188,198),white=Color.WHITE,muted=Color.rgb(175,195,198);
        UI(Context c){super(c);den=getResources().getDisplayMetrics().density;setFocusable(true);}
        float d(float x){return x*den;}void txt(Canvas c,String s,float x,float y,float z,int col,Paint.Align a){p.setStyle(Paint.Style.FILL);p.setColor(col);p.setTextSize(d(z));p.setTextAlign(a);c.drawText(s,x,y,p);}void box(Canvas c,float l,float t,float rr,float b,float rad,int col,boolean stroke){p.setStyle(stroke?Paint.Style.STROKE:Paint.Style.FILL);p.setStrokeWidth(d(1.2f));p.setColor(col);r.set(d(l),d(t),d(rr),d(b));c.drawRoundRect(r,d(rad),d(rad),p);}
        void refresh(){invalidate();}
        @Override protected void onDraw(Canvas c){c.drawColor(bg);float w=getWidth()/den;txt(c,"Al-othmany Sender",w-20,42*d(1),25,white,Paint.Align.RIGHT);txt(c,"الإصدار 4.1.0 • انضمام + نشر + استئناف",w-20,70,13,muted,Paint.Align.RIGHT);
            box(c,18,95,w-18,290,24,card,false);txt(c,"إدارة الروابط",w-38,132,23,white,Paint.Align.RIGHT);txt(c,"روابط دعوة WhatsApp • حذف التكرارات تلقائياً",w-38,158,13,muted,Paint.Align.RIGHT);box(c,45,180,w-45,232,26,Color.rgb(0,120,128),false);txt(c,"إضافة روابط",w/2,214,18,white,Paint.Align.CENTER);String q=state.links().size()+" رابط | المؤشر "+Math.min(state.index(),state.links().size())+"/"+state.links().size();txt(c,q,w-45,267,13,muted,Paint.Align.RIGHT);
            box(c,18,305,w-18,540,24,card,false);txt(c,"واتساب والملف الحالي",w-38,342,21,white,Paint.Align.RIGHT);txt(c,state.selectedPackage().isEmpty()?"لم يتم الاختيار":state.selectedPackage(),w-38,370,14,cyan,Paint.Align.RIGHT);box(c,45,390,w-45,438,24,line,true);txt(c,"اختيار تطبيق واتساب",w/2,421,16,white,Paint.Align.CENTER);box(c,45,450,w-45,498,24,line,true);txt(c,"فتح واتساب المحدد",w/2,481,16,white,Paint.Align.CENTER);
            box(c,18,555,w-18,840,24,card,false);txt(c,"النشر بعد الانضمام",w-38,592,20,white,Paint.Align.RIGHT);String pub=state.publishEnabled()?"مفعّل":"متوقف";txt(c,"الحالة: "+pub,w-38,620,14,cyan,Paint.Align.RIGHT);box(c,45,638,w-45,686,24,line,true);txt(c,"تفعيل/تعطيل النشر",w/2,669,16,white,Paint.Align.CENTER);box(c,45,696,w-45,744,24,line,true);txt(c,"تعديل رسالة النشر",w/2,727,16,white,Paint.Align.CENTER);txt(c,state.message().isEmpty()?"لا توجد رسالة محفوظة":state.message(),w-45,775,12,muted,Paint.Align.RIGHT);
            box(c,18,855,w-18,1100,24,card,false);String ph=status==null?"جاهز":status.phase;txt(c,ph,w-38,892,19,white,Paint.Align.RIGHT);String pr=status==null?"0 / "+state.links().size():status.done+" / "+status.total;txt(c,pr,w-45,920,14,cyan,Paint.Align.RIGHT);txt(c,"فشل: "+(status==null?state.failed().size():status.failed)+" | محاولة: "+(status==null?0:status.attempt),w-45,947,12,muted,Paint.Align.RIGHT);box(c,45,970,w-45,1022,26,cyan,false);txt(c,"بدء / استئناف",w/2,1003,17,white,Paint.Align.CENTER);box(c,45,1035,w/2-8,1083,24,line,true);txt(c,"إيقاف مؤقت",w/4,1066,14,white,Paint.Align.CENTER);box(c,w/2+8,1035,w-45,1083,24,line,true);txt(c,"إيقاف",w*0.75f,1066,14,white,Paint.Align.CENTER);
            box(c,45,1095,w-45,1140,22,line,true);txt(c,"إعداد خدمة الوصول (Accessibility)",w/2,1124,14,cyan,Paint.Align.CENTER);
        }
        @Override public boolean onTouchEvent(android.view.MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX()/den,y=e.getY()/den,w=getWidth()/den;if(y>=180&&y<=232){chooseLinks();return true;}if(y>=390&&y<=438){chooseWhatsapp();return true;}if(y>=450&&y<=498){openWhatsapp();return true;}if(y>=638&&y<=686){state.publishEnabled(!state.publishEnabled());refresh();return true;}if(y>=696&&y<=744){editMessage();return true;}if(y>=970&&y<=1022){start();return true;}if(y>=1035&&y<=1083&&x<w/2){pause();return true;}if(y>=1035&&y<=1083&&x>=w/2){stop();return true;}if(y>=1095&&y<=1140){accessibility();return true;}return true;}
    }
}
